### ISSUE TITLE
Strength reducing negative integers

### ISSUE THREAD

**Issue by albertsgarde** [ejmahler/strength_reduce#3]
Would it be possible to get the same speed-ups when dividing negative integers by positive integers?
This crate currently only supports dividing positive integers.

**Comment by ejmahler** [comment]
The logic in this crate can't be applied directly, since it relies pretty heavily on the exact bit layout of the numbers.

I'm sure there's a similar set of tricks that can be pulled, but I'm not aware of them. So the answer is generally yes, but I don't know how to do it.

Dividing by a negative number is equivalent to dividing by the absolute value, and negating the result, so it wouldn't be ideal, but  you could store a bool for the sign of the divisor, and negate the output if the divisor is negative.
